config/routes.rb
SegfaultMe::Application.routes.draw do
  SLUG_REGEX   = /[a-z\-]+/i
  PAGE_REGEX   = /\d+/
  TAG_REGEX    = %r{[^-\.'"\\/+&@#$\^&*]+}
  LOCALE_REGEX = /ja/

  scope "/(:locale)", :locale => LOCALE_REGEX do
    match 'about' => 'static#about'
    match 'portfolio' => 'static#portfolio'
    match 'resume' => 'static#resume'

    resources :tags, only: [:show], :constraints => { id: TAG_REGEX }

    # Manual routes to avoid resources.
    match 'page/:page' => 'articles#list', :constraints => { page: PAGE_REGEX }, as: :page, :defaults => { page: 1 }
    match 'posts/:slug' => 'articles#show', :constraints => { slug: SLUG_REGEX }, as: :article
    match 'posts/raw/:slug' => 'articles#raw', :constraints => { slug: SLUG_REGEX }, as: :raw
    match 'feed/rss' => 'articles#rss', as: :rss

    match '/404', :to => 'errors#error_404'
    match '/500', :to => 'errors#error_500'
    match '/503', :to => 'errors#error_503'
    root :to => 'articles#list'
  end
end

app/models/article.rb
# -*- coding: utf-8 -*-
class Article < ActiveRecord::Base
  SLUG_REGEX = /^[a-z]([a-z]|\-[^\-])*[a-z]*$/i
  RSS_CACHE = 'rss_cache'
  attr_accessible :allow_comments, :slug

  validates :allow_comments, presence: true
  validates :slug, presence: true,
                   length: {maximum: 255},
                   format: {with: SLUG_REGEX}

  has_many :translations, :dependent => :destroy
  default_scope { order "created_at DESC" }

  def date
    created_at.strftime '%B %d %Y' # TODO: Internationalize
  end

  def to_param
    slug
  end

  def title
    translation.header
  end

  def description
    translation.description
  end

  # Abstract API
  def tags
    translation.tags
  end

  def content
    translation.html_cache
  end

  def comments
    [] # TODO: Methood stub
  end

  def markdown
    translation.markdown
  end

  def self.page(page)
    joins(translations: :language).where("languages.code = '#{I18n.locale}'")
      .paginate(:page => page, :per_page => 6) # TODO: Move to APP_CONFIG?
  end

  def self.from_file(slug)
    @@md ||= Redcarpet::Markdown.new(Pygmentizer, :autolink => true, :fenced_code_blocks => true, :no_intra_emphasis => true)
    @@langs ||= Language.all

    logger.info "Article.from_file(#{slug})"
    a = Article.where(slug: slug).first_or_initialize # Create or update
    @@langs.each do |lang|
      path = Rails.root.join('public', 'articles', lang.code, "#{slug}.md")
      logger.debug "  Default lookup path is `#{path}`"
      begin
        md = IO.read(path)
        data = md.split /\n\n|\r\n\r\n/, 2 # Split at the first two consecutive line breaks.
        meta = Article.parse_metadata(data[0])
        meta["allow comments"] = true if !meta.has_key? "allow comments" # Allow comments by default.
        content = data[1]

        if lang.code == 'en' # FIXME: This should only be done if we have at least the fallback translation
          a.allow_comments = meta["allow comments"]
          begin
            a.created_at = DateTime.parse(meta["date"])  # Support persisting dates
          rescue
            a.created_at = nil # Will be added with current date.
          end if meta.has_key? 'date'
          a.save!
          logger.info "  Created article"
        end

        t = Translation.where(language_id: lang, article_id: a).first_or_initialize # Create or update translation
        t.language = lang
        t.article = a
        t.markdown = md
        t.html_cache = @@md.render(content)
        t.inject_metadata meta
        t.save!
        logger.info "  Added translation for #{lang.name}"
      rescue # FIXME: Better error handling.
        return nil if lang.code == 'en' # If we can't find the default language, no article is created.
      end
    end
    logger.info "  Cleared RSS cache"
    ActionController::Base.new.expire_fragment(Article::RSS_CACHE)
    return a
  end

  private
  def translation # TODO: Make private
    Translation.joins(:language).where("languages.code = '#{I18n.locale}'").find_by_article_id(self.id)
  end

  #private
  def self.parse_metadata(content)
    metadata = Hash.new()
    begin
      content.lines.each do |p|
        k, v = p.split ":", 2
        next if k == nil || v == nil
        metadata[k.strip.downcase] = v.strip
      end
    rescue # Parsing failed, return an empty or partial hash.
    end
    return metadata
  end
end

class Pygmentizer < Redcarpet::Render::HTML
  def block_code(code, language)
    require 'pygmentize'
    Pygmentize.process(code, language) if language
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def list
    @articles = Article.page(params[:page])
    # FIXME: use HTTP header accept-language instead of cookies.
  end

  def show
    @article = Article.where(:slug => params[:slug]).first!
  end

  def raw
    @article =  Article.where(:slug => params[:slug]).first!
    render :layout => false, :content_type => 'text/x-markdown'
  end

  def rss
    @articles = Article.order('created_at DESC').limit(10)
    render :layout => false, :content_type => 'application/xml'
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def render_newer(pages)
    link_to_if pages.current_page > 1, "Newer", pages.current_page - 1 == 1 ? root_path : page_path(params[:locale], pages.current_page - 1)
  end

  def render_older(pages)
    link_to_if pages.total_pages > pages.current_page, "Older", page_path(params[:locale], pages.current_page + 1)
  end
end

app/views/articles/_article.html.erb
<% provide(:title, article.title) %>
<article>
  <header>
    <span class="date"><%= article.date %><%= link_to "raw", raw_path(article) %></span>
    <h1><%= article.title %></h1>
    <!-- Licensing here -->
  </header>
<%== article.content %>

<footer>
  <section class="tags">
    Filed under <ul class="tags"><%= render article.tags %></ul>
  </section>
</footer>
</article>

app/views/articles/_article_list.html.erb
<li>
 <article>
  <span class="date"><%= article_list.date %></span>
  <h2><%= link_to article_list.title, article_path(article_list) %></h2>
 </article>
</li>

app/views/articles/_article_rss.html.erb
   <item>
    <title><%= article_rss.title %></title>
    <% if article_rss.description != nil %>
    <description><%= article_rss.description %></description>
    <% end %>
    <guid><%= article_url(article_rss) %></guid>
    <link><%= article_url(article_rss) %></link>
    <pubDate><%= article_rss.created_at.to_formatted_s :rfc822 %></pubDate>
   </item>

app/views/articles/list.html.erb
<% provide(:title, 'Home') %>
<ul class="blog"><% if @articles.empty? %><li>
  <article>
   There are no articles to display.
  </article>
 </li><% else %><%= render :partial => 'articles/article_list', :collection =>  @articles %><% end %></ul>
<div class="pages">
 <span class="prev"><%= render_newer @articles %></span>
 <span class="go"><%= render_older @articles %></span>
</div>

app/views/articles/raw.html.erb
<%== @article.markdown %>

app/views/articles/rss.html.erb
<% cache(Article::RSS_CACHE) do %>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
 <channel>
   <title>Segmentation Fault</title>
   <link><%= root_url %></link>
   <description>
    <%= t 'rss_desc' %>
   </description>
   <language><%= t 'rss_lang' %></language>
   <ttl>40</ttl>
   <lastBuildDate><%= Time.now.to_formatted_s :rfc822 %></lastBuildDate>
   <atom:link href="<%= rss_url %>" rel="self" type="application/rss+xml" />

<%= render :partial => 'articles/article_rss', :collection =>  @articles %>
 </channel>
</rss>
<% end %>

app/views/articles/show.html.erb
 <%= render @article %>