config/routes.rb
SegfaultMe::Application.routes.draw do
  SLUG_REGEX   = /[a-z\-]+/i
  PAGE_REGEX   = /\d+/
  TAG_REGEX    = %r{[^-\.'"\\/+&@#$\^&*]+}
  LOCALE_REGEX = /ja/

  scope "/(:locale)", :locale => LOCALE_REGEX do
    match 'about' => 'static#about'
    match 'portfolio' => 'static#portfolio'
    match 'resume' => 'static#resume'

    resources :tags, only: [:show], :constraints => { id: TAG_REGEX }

    # Manual routes to avoid resources.
    match 'page/:page' => 'articles#list', :constraints => { page: PAGE_REGEX }, as: :page, :defaults => { page: 1 }
    match 'posts/:slug' => 'articles#show', :constraints => { slug: SLUG_REGEX }, as: :article
    match 'posts/raw/:slug' => 'articles#raw', :constraints => { slug: SLUG_REGEX }, as: :raw
    match 'feed/rss' => 'articles#rss', as: :rss

    match '/404', :to => 'errors#error_404'
    match '/500', :to => 'errors#error_500'
    match '/503', :to => 'errors#error_503'
    root :to => 'articles#list'
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  validates :freq, presence: true
  validates :name, presence: true, length: {maximum: 50}

  has_many :taggings
  has_many :translations, :through => :taggings

  def to_param
    name
  end

  def self.from_name(name)
    t = Tag.find_or_create_by_name(name)
    return t
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    # Tag cloud or something
  end

  def show
    @articles = Article.joins({translations: { taggings: :tag }}).where("tags.name = '#{params[:id]}'")
    @title = params[:id]
  end
end

app/views/tags/_tag.html.erb
<li><%= link_to tag.name,  tag_path(tag) %></li>

app/views/tags/index.html.erb
Under Construction

app/views/tags/show.html.erb
<% provide(:title, @title) %>
<h1>Articles filed under <%= @title %></h1>
<ul class="blog"><% if @articles.empty? %><li>
 <article>
  There are no articles tagged <%= @title %>.
 </article>
</li><% else %><%= render :partial => 'articles/article_list', :collection => @articles %><% end %></ul>