config/routes.rb
SegfaultMe::Application.routes.draw do
  SLUG_REGEX   = /[a-z\-]+/i
  PAGE_REGEX   = /\d+/
  TAG_REGEX    = %r{[^-\.'"\\/+&@#$\^&*]+}
  LOCALE_REGEX = /ja/

  scope "/(:locale)", :locale => LOCALE_REGEX do
    match 'about' => 'static#about'
    match 'portfolio' => 'static#portfolio'
    match 'resume' => 'static#resume'

    resources :tags, only: [:show], :constraints => { id: TAG_REGEX }

    # Manual routes to avoid resources.
    match 'page/:page' => 'articles#list', :constraints => { page: PAGE_REGEX }, as: :page, :defaults => { page: 1 }
    match 'posts/:slug' => 'articles#show', :constraints => { slug: SLUG_REGEX }, as: :article
    match 'posts/raw/:slug' => 'articles#raw', :constraints => { slug: SLUG_REGEX }, as: :raw
    match 'feed/rss' => 'articles#rss', as: :rss

    match '/404', :to => 'errors#error_404'
    match '/500', :to => 'errors#error_500'
    match '/503', :to => 'errors#error_503'
    root :to => 'articles#list'
  end
end

app/views/layouts/_footer.html.erb
    </div><!--
    --><div class="side">
     <p><%= t "blurb_html" %></p>
     <p><%= t "blurb_cont_html" %></p>
     <div class="island">
      <h2><%= t "curproj_header" %></h2>
      <p><%= t "curproj_desc_html" %></p>
     </div>
    </div>
   </div>
  </div>
  <footer class="feet">
   <div class="c">
    <p><%= t "copyright_html" %></p>
    <p>
     <%= t "findme" %> <a href="https://twitter.com/alxbl">twitter</a>,
     <a href="http://webchat.freenode.net/">freenode</a>,
     <a href="http://www.github.com/alxbl">github</a>,
     <a href="https://bitbucket.org/alxbl">bitbucket</a>,
     <a href="http://stackoverflow.com/users/424216/alxbl">stack overflow</a>.
    </p>
    <ul class="tech">
     <li>Ruby Enterprise 1.8.7</li>
     <li>nginx 1.2.7</li>
     <li>inuit.css 5.0</li>
     <li>git 1.7.9</li>
    </ul>
   </div>
  </footer>
 </body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html<%== page_class yield(:title).downcase %> ng-app>
 <head>
  <meta charset="utf-8">
  <title><%= page_title yield(:title) %></title>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.9/angular.min.js"></script>
  <link href="http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Sans+Mono" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag "application", media: 'all' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 </head>
 <body>
  <div class="c">
   <header class="hat">
    <h1>Segmentation Fault</h1>
    <nav>
     <ul class="lang-nav">
      <li><%= link_to 'English', url_for(locale: nil), class: 'en' %></li>
      <li><%= link_to '日本語', url_for(locale: :ja), class: 'ja' %></li>
     </ul>
     <%= link_to image_tag("/segfault.svg", alt: "Segfault"), root_path, class: 'logo' %>
     <ul class="main-nav">
      <li class="nav-home"><%= link_to (t "home"), root_path %>
      <li class="nav-about"><%= link_to (t "about"), about_path %>
      <!--<li class="nav-portfolio"><%= link_to (t "portfolio"), portfolio_path %>-->
      <li><%= link_to "GitHub", 'https://www.github.com/alxbl' %>
      <li class="nav-resume"><%= link_to (t "resume"), resume_path %>
     </ul>
    </nav>
  </header>
  <div class="g"><!--
  --><div class="content">

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>
  <%= yield %>
<%= render 'layouts/footer' %>